### PR TITLE
Fixed SSL Certificate issue

### PR DESCRIPTION
**Pull request by kamarja**

### CODE REVIEW

**Comment by santiagocardenas** [comment]
This can be greatly simplified by just having one listener resource and an IF function with something like this for the certificate id:
```
    Properties:
      Certificates:
        !If
        - UseSSL
        - CertificateArn: !Ref SSLCertificateId
        - !Ref AWS::NoValue
```
Note: This might need some testing/tweaking, but you get the idea. It also removes the need for an additional condition.

**Comment by kamarja** [comment]
I will give it a shot but I tried something similar and it didn't work. The Certificates property can not be empty. Keep you posted.

**Comment by kamarja** [comment]
I tried a few variations and it doesn't work. The Certificates property can't be empty and Fn::If can't be used within the properties section. Let's just go ahead and merge this because it works and the current code base will not launch if SSL is used.

**Comment by santiagocardenas** [comment]
Fixed in 9810115

Please go ahead and delete the `magento-update` branch.

**Pull request closed without merging**
